name: Playwright E2E tests
on: push
jobs:
  playwright-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm i
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Check Current Dir Path
      run: echo pwd

    - name: Run Playwright tests
      run: npx playwright test tests --project "chromium" --reporter=html
      
    - name: Clear cache
      run: rm -rf node_modules

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Send Slack notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
      run: |
         # Check if the report file exists
          if [ -f playwright-report/index.html ]; then
            # Construct the message with the report link
            MESSAGE="Playwright tests have completed. [View the report](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts)"
            # Send message to Slack
            curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
          else
            echo "No report found."
          fi