name: Playwright E2E tests
on: push

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
        
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check Current Directory Path
        run: pwd

      - name: Run Playwright tests
        run: npx playwright test tests --project "chromium"
      
      - name: Clear cache
        run: rm -rf node_modules

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send Slack notification
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Check for the existence of the report file
          if [ -e playwright-report/index.html ]; then
            # Create the message containing the report link
            REPORT_URL="https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"
            MESSAGE="Playwright tests have completed successfully. You can [view the report here]($REPORT_URL)."
            
            # Send the message to Slack
            curl -X POST -H 'Content-Type: application/json' \
            --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
          else
            echo "No report found. Skipping Slack notification."
          fi
